---
- name: This sets up an apache server
  hosts: all
  remote_user: ec2-user
  become: yes
  vars_files:
        - vars/default.yml
  tasks:
    - name: Install apache packages 
      yum:
        name: httpd
        state: present
    - name: ensure httpd is running
      service:
        name: httpd 
        state: started
    - name: copy index page
      template:
        src: "files/index.html.j2"
        dest: "/var/www/html/index.html"
    - name: "install firewalld"
      yum:
        name: firewalld
        state: present
    - name: Open port {{ http_port }} for http access
      firewalld:
        service: http
        permanent: true
        state: enabled
    - name: Restart the firewalld service to load in the firewall changes
      service: 
        name: firewalld 
        state: restarted